apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: smart-ticketing
  labels:
    app: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: smart-ticketing/event-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: smart-ticketing-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /events/health/check
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /events/health/check
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: smart-ticketing
spec:
  selector:
    app: event-service
  ports:
    - port: 3002
      targetPort: 3002
