apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-ticketing-config
  namespace: smart-ticketing
data:
  AUTH_SERVICE_URL: "http://auth-service:3001"
  EVENT_SERVICE_URL: "http://event-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"
  CHECKIN_SERVICE_URL: "http://checkin-service:3004"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
  KAFKA_BROKER: "kafka:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: smart-ticketing-secret
  namespace: smart-ticketing
type: Opaque
stringData:
  JWT_SECRET: "dhbw-secret-2026"
